Repository lecture-developer/lecture_website_app_generator, pull requests merged in 2020-09, with the labels that each got.

#17 017 add logger
  README.md
  package-lock.json
  package.json
  src/server/logger.js
  src/server/server.js
  src/server/src/routes/users.js
Labels: enhancement

#18 31 add documentation and simplify be
  src/server/server.js
  src/server/src/routes/users.js
Labels: documentation

#19 18 replace smtp to gmail account
  README.md
  package-lock.json
  package.json
  src/server/email.js
  src/server/server.js
  src/server/src/routes/users.js
Labels: enhancement

#20 021 local storage
  README.md
  package.json
  src/client/src/App.js
  src/client/src/routes/IndexPage/components/IndexPage.js
  src/client/src/routes/IndexPage/components/ProjectsDetails.js
  src/client/src/routes/IndexPage/components/PublicationsDetails.js
  src/client/src/routes/IndexPage/components/ResearchDetails.js
  src/client/src/routes/LoginUserPage/components/LoginUser.js
  src/client/src/routes/PublicationsPage/components/PublicationsPage.js
  src/server/data/index-data.json
  src/server/data/publications-data.json
  src/server/data/users/5f53bae924e27d18580d4036/index.json
  src/server/data/users/undefined/publications.json
  src/server/src/resources/methods.js
  src/server/src/routes/index-page.js
  src/server/src/routes/publications.js
  src/server/src/routes/users.js
Labels: enhancement

#23 added hamburger for mobile menu. fixed header line logic to always keep on the same line
  src/client/public/index.html
  src/client/public/main.css
Labels: enhancement

#21 Mobile menu view
  src/client/public/contact-us.html
  src/client/public/index.html
  src/client/public/join-our-team.html
  src/client/public/main.css
  src/client/public/main.js
  src/client/public/sign-for-beta.html
  src/client/public/thank-you.html
Labels: bug, enhancement

#25 added 404 not found page.
  src/client/public/404.html
  src/client/public/main.css
Labels: enhancement

#26 Forms active
  src/client/public/main.css
  src/client/public/sign-for-beta.html
  src/client/public/sign-for-beta.js
Labels: enhancement

#31 Contact us design
  env
  src/client/public/contact-us.html
  src/client/public/main.css
  src/client/public/sign-for-beta.html
Labels: enhancement

#33 fixed 404 not-found page according to design (both desktop and mobile)
  src/client/public/404.html
  src/client/public/main.css
Labels: bug

#35 17 user didnt activate send x days and delete
  package-lock.json
  package.json
  src/server/email.js
  src/server/emailController.js
  src/server/server.js
  src/server/src/jobs/ActivationReminderJob.js
  src/server/src/models/user.js
  src/server/src/resources/emails.js
  src/server/src/routes/users.js
Labels: bug, enhancement

#34 fixed design
  src/client/public/main.css
  src/client/public/thank-you.html
  src/client/public/thankYou.js
Labels: bug
