Repository lecture-developer/lecture_website_app_generator, pull requests merged in 2020-10, with the labels that each got.

#39 Index mobile and desktop
  README.md
  env
  src/client/public/images/ArielAlexi.jpg
  src/client/public/images/hadarRobinzon.jpg
  src/client/public/images/index_mobile_1.png
  src/client/public/images/index_mobile_2.png
  src/client/public/images/mobile.png
  src/client/public/images/nadavSpitzer.jpg
  src/client/public/images/yaelMohaban.jpg
  src/client/public/index.html
  src/client/public/main.css
Labels: bug, enhancement

#42 Feature/forms redirect
  src/client/public/contact-us.html
  src/client/public/contact-us.js
  src/client/public/join-our-team.html
  src/client/public/join-our-team.js
  src/client/public/sign-for-beta.html
  src/client/public/sign-for-beta.js
  src/client/public/thank-you.html
  src/client/public/thankYou.js
  src/server/server.js
  src/server/src/resources/emails.js
  src/server/src/routes/contact-us.js
  src/server/src/routes/index.js
  src/server/src/routes/join-our-team.js
  src/server/src/routes/sign-for-beta.js
Labels: enhancement

#46 Some qa changes
  src/client/public/404.html
  src/client/public/contact-us.html
  src/client/public/index.html
  src/client/public/join-our-team.html
  src/client/public/join-us-as.html
  src/client/public/legal.html
  src/client/public/main.css
  src/client/public/main.js
  src/client/public/sign-for-beta.html
  src/client/public/thank-you.html
  src/client/public/thankYou.js
Labels: bug

#48 navbar changes, logo added and some text is changed
  src/client/public/404.html
  src/client/public/contact-us.html
  src/client/public/contact-us.js
  src/client/public/images/LOGOdeskt_footer.png
  src/client/public/images/LOGOdeskt_nav.png
  src/client/public/images/LOGOlogo.png
  src/client/public/images/LOGOmobil_footer.png
  src/client/public/images/LOGOmobil_nav.png
  src/client/public/index.html
  src/client/public/join-our-team.html
  src/client/public/join-our-team.js
  src/client/public/join-us-as.html
  src/client/public/legal.html
  src/client/public/main.css
  src/client/public/main.js
  src/client/public/sign-for-beta.html
  src/client/public/thank-you.html
  src/client/public/thankYou.js
Labels: bug

#50 css change
  src/client/public/404.html
  src/client/public/contact-us.html
  src/client/public/index.html
  src/client/public/join-our-team.html
  src/client/public/join-our-team.js
  src/client/public/join-us-as.html
  src/client/public/legal.html
  src/client/public/main.css
  src/client/public/sign-for-beta.html
  src/client/public/thank-you.html
Labels: bug

#51 Nadav qa fix
  src/client/public/main.css
  src/client/public/thank-you.html
  src/client/public/thankYou.js
Labels: bug

#54 with css changes
  src/client/public/contact-us.html
  src/client/public/index.html
  src/client/public/join-our-team.html
  src/client/public/join-our-team.js
  src/client/public/join-us-as.js
  src/client/public/legal.html
  src/client/public/main.css
  src/client/public/thank-you.html
  src/client/public/thankYou.js
Labels: bug
